*** Variables ***

# messages
${MSG001_contact_us}    Success! Your details have been submitted successfully.

# data
${contact_name}       Contact User
${contact_email}      contact.user@example.com
${contact_subject}    Contact Us Automation Test
${contact_message}    This is a test message submitted by Robot Framework.

# files
${contact_us_attachment_path}    ${EXECDIR}${/}resources${/}pdf${/}contact_us_attachment.pdf
